#!/usr/bin/env python3

"""A Diceware-style Password Generator"""

import argparse
import math
import random
import string
import sys
from typing import Callable, Sequence

__version__ = '2.0.0'

CONSOLE_SCRIPT = 'keysmith'

POPULATIONS = {
    'alphanumeric': string.ascii_letters + string.digits,
    'ascii_letters': string.ascii_letters,
    'digits': string.digits,
    'printable': string.printable,
}


def build_cli(parser: argparse.ArgumentParser) -> None:
    """Build a parser for CLI arguments and options."""
    parser.add_argument(
        '-d', '--delimiter',
        help='a delimiter for the samples (teeth) in the key',
        default=' ',
    )
    parser.add_argument(
        '-n', '--nsamples',
        help='the number of random samples to take',
        type=int,
        default=6,
        dest='nteeth',
    )
    parser.add_argument(
        '-p', '--population',
        help=', '.join(POPULATIONS.keys()) + ', or a path to a file of line-delimited items',
        default='/usr/share/dict/words',
    )
    parser.add_argument(
        '--encoding',
        help='the encoding of the population file'
             ' (see https://docs.python.org/3/library/codecs.html#standard-encodings)',
        default='utf-8',
    )
    parser.add_argument(
        '--stats',
        help='show statistics for the key',
        default=False,
        action='store_true',
    )
    parser.add_argument(
        '--version',
        action='version',
        version='%(prog)s {0}'.format(__version__),
    )


def cli() -> argparse.ArgumentParser:
    """Create a parser for CLI arguments and options."""
    parser = argparse.ArgumentParser(
        prog=CONSOLE_SCRIPT,
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    build_cli(parser)
    return parser


def key(
        seq: Sequence,
        tooth: Callable[[Sequence], str] = (
            lambda seq: str(random.SystemRandom().choice(seq)).strip()
        ),
        nteeth: int = 6,
        delimiter: str = ' ',
):
    """Concatenate strings generated by the tooth function."""
    return delimiter.join(tooth(seq) for _ in range(nteeth))


def main(argv: Sequence[str] = tuple(sys.argv[1:])):
    """Execute CLI commands."""

    args = cli().parse_args(argv)

    seq = POPULATIONS.get(args.population)  # type: Sequence
    if seq is None:
        try:
            with open(args.population, 'r', encoding=args.encoding) as f:
                seq = list(f)
        except (OSError, UnicodeError) as ex:
            print(ex, file=sys.stderr)
            return 1

    main_key = key(seq=seq, nteeth=args.nteeth, delimiter=args.delimiter)
    print(main_key)

    if args.stats:
        print('* {0} characters'.format(len(main_key)))
        print('* {0} samples from a population of {1}'.format(args.nteeth, len(seq)))
        print('* entropy {sign} {bits} bits'.format(
            sign='<' if len(args.delimiter) < 1 else '~',
            bits=round(math.log(len(seq), 2) * args.nteeth, 2),
        ))

    return 0


if __name__ == '__main__':
    sys.exit(main())
